### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by alonbg**
downloads the go tarball, compares checksum, applies patch and uses it to build

### CODE REVIEW

**Comment by FaisalRGoraya** [comment]
Currently, I am trying to compile wireguard and I am facing this issue, "Command ExternalBuildToolExecution failed with a nonzero exit code". Can anyone guide me on how can I fix this??
Regards,
Faisal Goraya

**Comment by dashvlas** [comment]
> Currently, I am trying to compile wireguard and I am facing this issue, "Command ExternalBuildToolExecution failed with a nonzero exit code". Can anyone guide me on how can I fix this??
> Regards,
> Faisal Goraya

same here :(

**Comment by FaisalRGoraya** [comment]
Hmmm, :(

**Comment by ZhangYanChao** [comment]
I tried this changed Makefile,but  "Command ExternalBuildToolExecution failed with a nonzero exit code" this issue still。and more error logs
"
Hunk #1 FAILED at 440.
1 out of 1 hunk FAILED -- saving rejects to file -
patching file src/runtime/sys_darwin_amd64.s
Hunk #1 succeeded at 97 (offset -17 lines).
patching file src/runtime/sys_darwin_arm64.s
Hunk #1 succeeded at 121 (offset -22 lines).
*** [/Users/zyc/Downloads/wireguard-apple/build/WireGuard.build/Debug-iphoneos/wireguard-go-bridge/go-1.13.4/.prepared] Error 1
"
Can anyone guide me on how can I fix this??

**Comment by miachel-lv** [comment]
I am facing "Command ExternalBuildToolExecution failed with a nonzero exit code" issue from compile too, anyone knows how to fix this, thanks!!!

**Comment by shinto-shintzz** [comment]
@ZhangYanChao  hey are you able to fix the issue

**Comment by keeshux** [comment]
Check out #6 for the issue you are experiencing.

**Comment by alonbg** [comment]
depricated

**Comment by shikanoji** [comment]
Any one know how to fix this on M1?

**Pull request closed without merging**
